require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe UsersController do

 before :each do
    @attr = { :name => "Name", :email => "mail@domain.com", :password => "pass", :password_confirmation =>"pass"}
  end

  describe "get index" do
    it "should have a successful response" do
      get :index
      response.should be_success
    end
  end

  describe "get show" do
    it "should be able to see a user" do
      #we create a user to see it
      User.create @attr
      get :show, :id =>1
      response.should be_success
    end
  end

  describe "get new" do
    it "should have a successful response" do
      get :new
      response.should be_success
    end
  end

  describe "get edit" do
    it "should have not be successful because not connected" do
      #we create a user to edit it
      User.create @attr
      get :edit, :id =>1
      response.should_not be_success
    end
  end

  describe "User creation success" do

    it "should create a user" do
      lambda do
        post :create, :user => @attr
        end.should change(User, :count).by(1)
    end

    it "should be redirected to the user" do
      post :create, :user => @attr
      response.should redirect_to(user_path(assigns(:user)))
    end
  end

  describe "User update success" do
    before :each do
      #we create a user to edit it
      User.create @attr
    end

    it "should edit a user" do
      #TODO !!!
    end

    it "should be redirected to the user" do
      #we create an other one to edit the first one with
      u = User.new
      u.name = "new"
      post :update, :id =>1, :user => u
      response.should redirect_to(user_path(assigns(:user)))
    end
  end

  describe "User destroy success" do
    before :each do
      #we create a user to destroy it
      User.create @attr
    end

    it "should destroy a user" do
      puts User.find(1).id
      lambda do
        post :destroy, :id => 1
      end.should change(User, :count).by(-1)
    end

    it "should redirect to the index of users" do
      post :destroy, :id => 1
      response.should redirect_to(users_path)
    end
  end
end
